#block-power
endfield-plasma-battery = endfield-crystal-battery
endfield-armored-battery = endfield-armored-crystal-battery

#block-environment
endfield-crystals = endfield-ore-cluster-crystal
endfield-crystals-boulder = endfield-ore-cluster-crystal
endfield-pooled-crystal-fluid = endfield-pooled-cold-plasma
endfield-pooled-deep-crystal-fluid =  endfield-pooled-deep-cold-plasma

#item
#pyratite = endfield-burn-compound

#liquid
endfield-crystal-fluid = endfield-cold-plasma